config/routes.rb
Maxitesting::Application.routes.draw do
  devise_for :users
  get "home_page/show"
  resources :campaigns
  post '/campaigns/:id/statuses' => 'campaigns#update_statuses'

  resources :browsers

  root 'home_page#show'

=begin
  match '/#' => redirect('/')
=end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Maxyactions" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= javascript_include_tag "application" %>

</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag('logo2.png'), root_path, :class => 'maxyLogo' %>
      <%= link_to "MaxyActions", root_path, :class => 'brand' %>

      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Browsers", browsers_path %></li>
          <li><%= link_to "Campaigns", campaigns_path %></li>
        </ul>

        <div class="nav pull-right">
          <% if user_signed_in? %>
              <%= current_user.email %> |
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          <% else %>
              <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
        </div>
      </div>

      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <!--/span-->
  </div>
  <!--/row-->

  <footer>
    <p class="copyright">&copy; Maxymiser 2014</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>